fixtures_path: 'Resources/fixtures' # Path to which to look for fixtures relative to the project directory or the bundle path.
root_dirs:
  - '%kernel.root_dir%'
  - '%kernel.project_dir%'

App\Entity\Allergens:
  allergens_{1..10}:
    name: <name()>
App\Entity\Ingredients:
  ingredients_{1..10}:
    name: <name()>
    ingredientsAllergens: '@allergens_*'
App\Entity\Dishes:
  dishes_{1..10}:
    name: <name()>
    description: 'Descripcion del plato'
    calories: '15 kcl'
    price: '10.50'
    ingredientsDishes: '@ingredients_*'

